version: "3"

tasks:
  test:utils:
    desc: Run utils tests
    dir: packages/utils
    cmds:
      - uv run pytest tests/ -v

  test:backtester:
    desc: Run backtester tests
    dir: packages/backtester
    cmds:
      - uv run pytest tests/ -v

  test:
    desc: Run all tests
    cmds:
      - task: test:utils
      - task: test:backtester
